### ISSUE TITLE
epicの使い方みっる

### ISSUE THREAD

**Issue by Tamiyas** [KatLab-MiyazakiUniv/learn-zenhub#5]
https://qiita.com/suzuki-hoge/items/f02b6752d8876ba6e114#%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%83%97%E3%83%A9%E3%83%B3%E3%83%8B%E3%83%B3%E3%82%B0%E3%82%92%E3%81%97%E3%82%88%E3%81%86

**Comment by korosuke613** [comment]
俺は見終わったよ
後は @Tatsumi0000 だけ
